// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cryptchatprotos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CryptChatProtos {

  /// <summary>Holder for reflection information generated from cryptchatprotos.proto</summary>
  public static partial class CryptchatprotosReflection {

    #region Descriptor
    /// <summary>File descriptor for cryptchatprotos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CryptchatprotosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVjcnlwdGNoYXRwcm90b3MucHJvdG8SD2NyeXB0Y2hhdHByb3RvcxoPcmVz",
            "cG9uc2VzLnByb3RvQhKqAg9DcnlwdENoYXRQcm90b3NQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CryptChatProtos.Responses.ResponsesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
