# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='cryptchatprotos.responses.account',
  syntax='proto3',
  serialized_options=_b('\252\002!CryptChatProtos.Responses.Account'),
  serialized_pb=_b('\n\raccount.proto\x12!cryptchatprotos.responses.account\"\'\n\x16\x43hangePasswordResponse\x12\r\n\x05token\x18\x01 \x01(\tB$\xaa\x02!CryptChatProtos.Responses.Accountb\x06proto3')
)




_CHANGEPASSWORDRESPONSE = _descriptor.Descriptor(
  name='ChangePasswordResponse',
  full_name='cryptchatprotos.responses.account.ChangePasswordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.responses.account.ChangePasswordResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['ChangePasswordResponse'] = _CHANGEPASSWORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangePasswordResponse = _reflection.GeneratedProtocolMessageType('ChangePasswordResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEPASSWORDRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.responses.account.ChangePasswordResponse)
  })
_sym_db.RegisterMessage(ChangePasswordResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
