# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='cryptchatprotos.responses.chat',
  syntax='proto3',
  serialized_options=_b('\252\002\036CryptChatProtos.Responses.Chat'),
  serialized_pb=_b('\n\nchat.proto\x12\x1e\x63ryptchatprotos.responses.chat\"@\n\rQueueResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x03(\t\x12\x0e\n\x06\x65\x64ited\x18\x02 \x03(\t\x12\x0e\n\x06resync\x18\x03 \x03(\t\"?\n\x0c\x43hatResponse\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0f\n\x07members\x18\x02 \x03(\t\x12\x11\n\tmsg_count\x18\x03 \x01(\x05\"O\n\x10\x43hatListResponse\x12;\n\x05\x63hats\x18\x01 \x03(\x0b\x32,.cryptchatprotos.responses.chat.ChatResponseB!\xaa\x02\x1e\x43ryptChatProtos.Responses.Chatb\x06proto3')
)




_QUEUERESPONSE = _descriptor.Descriptor(
  name='QueueResponse',
  full_name='cryptchatprotos.responses.chat.QueueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='cryptchatprotos.responses.chat.QueueResponse.deleted', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edited', full_name='cryptchatprotos.responses.chat.QueueResponse.edited', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resync', full_name='cryptchatprotos.responses.chat.QueueResponse.resync', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=110,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='cryptchatprotos.responses.chat.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='cryptchatprotos.responses.chat.ChatResponse._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='members', full_name='cryptchatprotos.responses.chat.ChatResponse.members', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='cryptchatprotos.responses.chat.ChatResponse.msg_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=175,
)


_CHATLISTRESPONSE = _descriptor.Descriptor(
  name='ChatListResponse',
  full_name='cryptchatprotos.responses.chat.ChatListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chats', full_name='cryptchatprotos.responses.chat.ChatListResponse.chats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=256,
)

_CHATLISTRESPONSE.fields_by_name['chats'].message_type = _CHATRESPONSE
DESCRIPTOR.message_types_by_name['QueueResponse'] = _QUEUERESPONSE
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
DESCRIPTOR.message_types_by_name['ChatListResponse'] = _CHATLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueueResponse = _reflection.GeneratedProtocolMessageType('QueueResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUEUERESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.responses.chat.QueueResponse)
  })
_sym_db.RegisterMessage(QueueResponse)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.responses.chat.ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)

ChatListResponse = _reflection.GeneratedProtocolMessageType('ChatListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATLISTRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.responses.chat.ChatListResponse)
  })
_sym_db.RegisterMessage(ChatListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
