# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: responses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2
import chat_pb2 as chat__pb2
import account_pb2 as account__pb2
import auth_pb2 as auth__pb2

from message_pb2 import *
from chat_pb2 import *
from account_pb2 import *
from auth_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='responses.proto',
  package='cryptchatprotos.responses',
  syntax='proto3',
  serialized_options=_b('\252\002\031CryptChatProtos.Responses'),
  serialized_pb=_b('\n\x0fresponses.proto\x12\x19\x63ryptchatprotos.responses\x1a\rmessage.proto\x1a\nchat.proto\x1a\raccount.proto\x1a\nauth.proto\"G\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0f\n\x07message\x18\x04 \x01(\tB\x1c\xaa\x02\x19\x43ryptChatProtos.ResponsesP\x00P\x01P\x02P\x03\x62\x06proto3')
  ,
  dependencies=[message__pb2.DESCRIPTOR,chat__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,auth__pb2.DESCRIPTOR,],
  public_dependencies=[message__pb2.DESCRIPTOR,chat__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,auth__pb2.DESCRIPTOR,])




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='cryptchatprotos.responses.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='cryptchatprotos.responses.Response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='cryptchatprotos.responses.Response.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cryptchatprotos.responses.Response.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='cryptchatprotos.responses.Response.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'responses_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.responses.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
