# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='cryptchatprotos.requests.account',
  syntax='proto3',
  serialized_options=_b('\252\002 CryptChatProtos.Requests.Account'),
  serialized_pb=_b('\n\raccount.proto\x12 cryptchatprotos.requests.account\"h\n\x15\x43hangePasswordRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08old_hash\x18\x02 \x01(\t\x12\x10\n\x08new_hash\x18\x03 \x01(\t\x12\x0e\n\x06pubkey\x18\x04 \x01(\t\x12\x0c\n\x04salt\x18\x05 \x01(\tB#\xaa\x02 CryptChatProtos.Requests.Accountb\x06proto3')
)




_CHANGEPASSWORDREQUEST = _descriptor.Descriptor(
  name='ChangePasswordRequest',
  full_name='cryptchatprotos.requests.account.ChangePasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.requests.account.ChangePasswordRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='old_hash', full_name='cryptchatprotos.requests.account.ChangePasswordRequest.old_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_hash', full_name='cryptchatprotos.requests.account.ChangePasswordRequest.new_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='cryptchatprotos.requests.account.ChangePasswordRequest.pubkey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salt', full_name='cryptchatprotos.requests.account.ChangePasswordRequest.salt', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ChangePasswordRequest'] = _CHANGEPASSWORDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangePasswordRequest = _reflection.GeneratedProtocolMessageType('ChangePasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEPASSWORDREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.account.ChangePasswordRequest)
  })
_sym_db.RegisterMessage(ChangePasswordRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
