# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='cryptchatprotos.requests.auth',
  syntax='proto3',
  serialized_options=_b('\252\002\035CryptChatProtos.Requests.Auth'),
  serialized_pb=_b('\n\nauth.proto\x12\x1d\x63ryptchatprotos.requests.auth\"\x1f\n\x0bSaltRequest\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"O\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0e\n\x06pubkey\x18\x03 \x01(\t\x12\x0c\n\x04salt\x18\x04 \x01(\tB \xaa\x02\x1d\x43ryptChatProtos.Requests.Authb\x06proto3')
)




_SALTREQUEST = _descriptor.Descriptor(
  name='SaltRequest',
  full_name='cryptchatprotos.requests.auth.SaltRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cryptchatprotos.requests.auth.SaltRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=76,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='cryptchatprotos.requests.auth.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cryptchatprotos.requests.auth.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='cryptchatprotos.requests.auth.LoginRequest.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=124,
)


_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='cryptchatprotos.requests.auth.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cryptchatprotos.requests.auth.UserRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=157,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='cryptchatprotos.requests.auth.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cryptchatprotos.requests.auth.RegisterRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='cryptchatprotos.requests.auth.RegisterRequest.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='cryptchatprotos.requests.auth.RegisterRequest.pubkey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salt', full_name='cryptchatprotos.requests.auth.RegisterRequest.salt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['SaltRequest'] = _SALTREQUEST
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaltRequest = _reflection.GeneratedProtocolMessageType('SaltRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALTREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.auth.SaltRequest)
  })
_sym_db.RegisterMessage(SaltRequest)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.auth.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.auth.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.auth.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
