# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='cryptchatprotos.requests.chat',
  syntax='proto3',
  serialized_options=_b('\252\002\035CryptChatProtos.Requests.Chat'),
  serialized_pb=_b('\n\nchat.proto\x12\x1d\x63ryptchatprotos.requests.chat\"*\n\x0cQueueRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\")\n\x0b\x43hatRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\" \n\x0f\x43hatListRequest\x12\r\n\x05token\x18\x01 \x01(\t\"8\n\nNewRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\x12\x0e\n\x06oldest\x18\x03 \x01(\x01\x42 \xaa\x02\x1d\x43ryptChatProtos.Requests.Chatb\x06proto3')
)




_QUEUEREQUEST = _descriptor.Descriptor(
  name='QueueRequest',
  full_name='cryptchatprotos.requests.chat.QueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.requests.chat.QueueRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='cryptchatprotos.requests.chat.QueueRequest._id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=87,
)


_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='cryptchatprotos.requests.chat.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.requests.chat.ChatRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='cryptchatprotos.requests.chat.ChatRequest._id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=130,
)


_CHATLISTREQUEST = _descriptor.Descriptor(
  name='ChatListRequest',
  full_name='cryptchatprotos.requests.chat.ChatListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.requests.chat.ChatListRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=164,
)


_NEWREQUEST = _descriptor.Descriptor(
  name='NewRequest',
  full_name='cryptchatprotos.requests.chat.NewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='cryptchatprotos.requests.chat.NewRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='cryptchatprotos.requests.chat.NewRequest._id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oldest', full_name='cryptchatprotos.requests.chat.NewRequest.oldest', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['QueueRequest'] = _QUEUEREQUEST
DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['ChatListRequest'] = _CHATLISTREQUEST
DESCRIPTOR.message_types_by_name['NewRequest'] = _NEWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueueRequest = _reflection.GeneratedProtocolMessageType('QueueRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.chat.QueueRequest)
  })
_sym_db.RegisterMessage(QueueRequest)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.chat.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatListRequest = _reflection.GeneratedProtocolMessageType('ChatListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATLISTREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.chat.ChatListRequest)
  })
_sym_db.RegisterMessage(ChatListRequest)

NewRequest = _reflection.GeneratedProtocolMessageType('NewRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.chat.NewRequest)
  })
_sym_db.RegisterMessage(NewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
