# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2
import chat_pb2 as chat__pb2
import account_pb2 as account__pb2
import auth_pb2 as auth__pb2

from message_pb2 import *
from chat_pb2 import *
from account_pb2 import *
from auth_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='requests.proto',
  package='cryptchatprotos.requests',
  syntax='proto3',
  serialized_options=_b('\252\002\030CryptChatProtos.Requests'),
  serialized_pb=_b('\n\x0erequests.proto\x12\x18\x63ryptchatprotos.requests\x1a\rmessage.proto\x1a\nchat.proto\x1a\raccount.proto\x1a\nauth.proto\"%\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x1b\xaa\x02\x18\x43ryptChatProtos.RequestsP\x00P\x01P\x02P\x03\x62\x06proto3')
  ,
  dependencies=[message__pb2.DESCRIPTOR,chat__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,auth__pb2.DESCRIPTOR,],
  public_dependencies=[message__pb2.DESCRIPTOR,chat__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,auth__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='cryptchatprotos.requests.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cryptchatprotos.requests.Request.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cryptchatprotos.requests.Request.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'requests_pb2'
  # @@protoc_insertion_point(class_scope:cryptchatprotos.requests.Request)
  })
_sym_db.RegisterMessage(Request)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
